### ISSUE TITLE
After opening Help > About, it wont quit and cannot use the application

### ISSUE THREAD

**Issue by tariqrahiman** [hammerui/hammerui_com#1]
If you take Help > About in the Windows "portable app package" it wont quit. The application needs to be closed and restarted.
Users cannot use the app if Help > About is opened

**Comment by hammerui** [comment]
Hi tariq

To close "About" window you need to hit Escape key on your keyboard. Can you try that?
I will make sure it's also described in the documentation.

**Comment by hammerui** [comment]
Hi tariq
I have released small fix for this ticket. I added "X" button to close the window. 
In the future I will add mechanism to close window if user clicks anywhere outside. 
New version 1.1 is available at https://hammerui.com/download.html

**Comment by tariqrahiman** [comment]
Fixed in 1.1
