### ISSUE TITLE
Feature Request : Close multiple opened Requests tab

### ISSUE THREAD

**Issue by tariqrahiman** [hammerui/hammerui_com#2]
This is a feature request for Close multiple opened Tabs - UI related.
Not related to functionality
If user has multiple tabs open, he can right click and close all tabs at once.
Would be useful if there are many opened Requests tabs.

just something to consider in the future.
![feature-2](https://user-images.githubusercontent.com/913554/103740657-850b1f80-4fac-11eb-9101-aecbcff7727e.png)

**Comment by hammerui** [comment]
I have added new Menu option called "View" with "Close all tabs" item. This is available in latest version 1.2.

I will also add context menu to the tabs panel in next release with more options like closing other tabs, or tabs on the right etc.

Waldemar

**Comment by tariqrahiman** [comment]
Fixed in 1.2
