### ISSUE TITLE
Executor Log : Save Log options

### ISSUE THREAD

**Issue by tariqrahiman** [hammerui/hammerui_com#3]
Executor Log : Save Log option feature
Can i save the log files of current execution in my local disk

**Comment by hammerui** [comment]
Execution log is just a text area so you can copy/paste from there, but I also added new feature to export log to a file. 
This is available in the latest version 1.2.

Waldemar

**Comment by tariqrahiman** [comment]
Great.. Can you make the name execution_log instead of execution?

**Comment by hammerui** [comment]
sure, no problem.

Waldemar
