### ISSUE TITLE
Executor Log: Keep the window open while testing

### ISSUE THREAD

**Issue by tariqrahiman** [hammerui/hammerui_com#4]
Executor Log: Keep the window open while testing
I have dual monitors and would like a feature to keep the Executor Log window opened and still able to run the tests.
With current build, if Executor Log is opened, then I cannot continue testing

**Comment by hammerui** [comment]
Sure, I have added this in the latest version 1.2.

Waldemar

**Comment by tariqrahiman** [comment]
Fixed in 1.2
