### ISSUE TITLE
HammerUI : File version shows 1.0.0.0 for 1.1 build

### ISSUE THREAD

**Issue by tariqrahiman** [hammerui/hammerui_com#5]
HammerUI : File version shows 1.0.0.0
The main version is 1.1
Nothing wrong in the functionality - just for consistent build purposes

![build-version](https://user-images.githubusercontent.com/913554/103741827-a40ab100-4fae-11eb-820a-eebb2356992b.png)

**Comment by hammerui** [comment]
I've fixed it in the latest version 1.2. 

Waldemar

**Comment by tariqrahiman** [comment]
Fixed in latest build
